version: "3"

services:
  local_dns:
    image: "${MAINTAINER}/${PROJECT}:${VERSION}"
    container_name: "${BIND9_CONTAINER_NAME}"
    env_file: .env
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./volumes/bind:/data/bind:rw
    networks:
      lab_network:
        ipv4_address: "${LAB_NAMESERVER}"

networks:
  lab_network:
    external: true
    name: "${DOCKER_NETWORK_NAME}"
