version: "3"

services:
  local_dns:
    image: "${MAINTAINER}/${PROJECT}:${VERSION}"
    container_name: "${CONTAINER_NAME}"
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns:/data:rw
